AWSTemplateFormatVersion: '2010-09-09'

Resources:

  PipelineBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: 'Private'

Outputs:
  PipelineBucket:
    Value: !Ref PipelineBucket
